env:
  browser: true
  es2020: true
extends:
  - airbnb-base
  - "plugin:jest/recommended"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  "import/prefer-default-export": "off",
  "no-param-reassign": [2, {"props": false}]
}
settings:
  import/resolver: webpack
